CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "roles_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "description" varchar(30) NOT NULL,
  "level" varchar(20) NOT NULL,
  "teacher" varchar(30) NOT NULL
);

CREATE TABLE "courses_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(30) NOT NULL,
  "category_id" int,
  "course_id" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "courses_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "course_id" int
);

ALTER TABLE "users" ADD FOREIGN KEY ("roles_id") REFERENCES "roles" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

INSERT INTO roles (name) VALUES ('Student'), ('Teacher'), ('Admin');

INSERT INTO courses (title, description, level, teacher) VALUES ('HTML', 'Desarrollo web', 'Easy', 'Alejandra'), ('CSS', ' Estetica web', 'Mid', 'Alejandra'), ('SQL', 'Base datos', 'Hard', 'Ian');

INSERT INTO categories (name) VALUES ('Fronted'), ('Backend');

INSERT INTO users (name, email, password, age, roles_id) VALUES ('Denis', 'denis@correo.com', 'denis', 27, 1), ('Joyce', 'joyce@correo.com', 'joyce', 27, 1), ('Carlo', 'carlo@correo.com', 'carlo', 27, 1);

INSERT INTO users_courses (user_id, course_id) VALUES (1, 1), (1, 2), (2, 1), (2, 2), (3, 2), (3, 3);

INSERT INTO courses_categories (category_id, course_id) VALUES (1, 1), (1, 2), (2, 3);

INSERT INTO courses_videos (title, url, category_id, course_id) VALUES ('HTML', 'HTML1', 1, 1), ('CSS', 'CSS1', 1, 2), ('SQL', 'SQL1', 2, 3);



